// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkT3toDTX3VNRLzi_RGPJvKSYNuV-RE-c',
    appId: '1:863996272719:web:fbcdfce633c0fc89828a3a',
    messagingSenderId: '863996272719',
    projectId: 'graduation-project-c079b',
    authDomain: 'graduation-project-c079b.firebaseapp.com',
    storageBucket: 'graduation-project-c079b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAikoPj7-kXXaY8gSG5VRGarZlozhBiQoc',
    appId: '1:863996272719:android:a3b42e9555ae3d0f828a3a',
    messagingSenderId: '863996272719',
    projectId: 'graduation-project-c079b',
    storageBucket: 'graduation-project-c079b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt14BGSTXfgilIoOnC7XZhEH94eDRmbHQ',
    appId: '1:863996272719:ios:08bba8c6d22823b7828a3a',
    messagingSenderId: '863996272719',
    projectId: 'graduation-project-c079b',
    storageBucket: 'graduation-project-c079b.appspot.com',
    iosBundleId: 'com.example.graduationproject',
  );
}
